/**
 * 功能：渐变色大全子页
 * 作者：FullStack-Guardian
 * 更新时间：2025-12-31
 */
import React, { useState } from 'react';
import PageContainer from '../../components/PageContainer';
import { motion } from 'framer-motion';
import { Info, Palette, Sparkles, Layout } from 'lucide-react';
import { useToastStore } from '../../store/toastStore';
import { copyToClipboard } from '../../utils/clipboard';

type Category = 'CSS' | '小清新' | '优雅';

interface GradientInfo {
  name: string;
  colors: string[];
  direction: string;
  category: Category;
}

const gradients: GradientInfo[] = [
  { name: 'Indigo Night', colors: ['#6366f1', '#a855f7'], direction: 'to right', category: 'CSS' },
  { name: 'Ocean Breeze', colors: ['#0ea5e9', '#22d3ee'], direction: 'to bottom right', category: 'CSS' },
  { name: 'Sunset Glow', colors: ['#f43f5e', '#fbbf24'], direction: 'to right', category: 'CSS' },
  { name: 'Forest Mist', colors: ['#10b981', '#34d399'], direction: 'to top right', category: 'CSS' },
  { name: 'Royal Purple', colors: ['#7c3aed', '#db2777'], direction: 'to bottom right', category: 'CSS' },
  { name: 'Morning Sky', colors: ['#38bdf8', '#818cf8'], direction: 'to right', category: 'CSS' },
  { name: 'Lush Green', colors: ['#22c55e', '#10b981'], direction: 'to right', category: 'CSS' },
  { name: 'Burning Orange', colors: ['#f97316', '#ef4444'], direction: 'to top', category: 'CSS' },
  { name: 'Slate Gray', colors: ['#475569', '#1e293b'], direction: 'to bottom', category: 'CSS' },
  { name: 'Sunset Orange', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: 'CSS' },
  { name: 'Soft Gray', colors: ['#E0E0E0', '#FFFFFF'], direction: 'to right', category: 'CSS' },
  { name: 'Deep Sea', colors: ['#2C3E50', '#4CA1AF'], direction: 'to right', category: 'CSS' },
  { name: 'Mango', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: 'CSS' },
  { name: 'Blue Lagoon', colors: ['#00B4DB', '#0083B0'], direction: 'to right', category: 'CSS' },
  { name: 'Purple Bliss', colors: ['#A18CD1', '#FBC2EB'], direction: 'to top', category: 'CSS' },
  { name: 'Summer Sky', colors: ['#84FAB0', '#8FD3F4'], direction: 'to right', category: 'CSS' },
  { name: 'Peach', colors: ['#FFD1FF', '#FAE1CB'], direction: 'to right', category: 'CSS' },
  { name: 'Mint', colors: ['#00FF87', '#60EFFF'], direction: 'to bottom right', category: 'CSS' },
  { name: 'Rose Water', colors: ['#E55D87', '#5FC3E4'], direction: 'to right', category: 'CSS' },
  { name: 'Purple Love', colors: ['#CC2B5E', '#753A88'], direction: 'to right', category: 'CSS' },
  { name: 'Fresh Green', colors: ['#9DFF95', '#11FFBD'], direction: 'to top', category: 'CSS' },
  { name: 'Vibrant Blue', colors: ['#0575E6', '#021B79'], direction: 'to bottom', category: 'CSS' },
  { name: 'Neon Life', colors: ['#B3FFAB', '#12FFF7'], direction: 'to right', category: 'CSS' },
  { name: 'Strawberry', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: 'CSS' },
  { name: 'Frost', colors: ['#000428', '#004e92'], direction: 'to top', category: 'CSS' },
  { name: 'Evening Sunshine', colors: ['#b92b27', '#1565C0'], direction: 'to bottom', category: 'CSS' },
  { name: 'Lush', colors: ['#56ab2f', '#a8e063'], direction: 'to right', category: 'CSS' },
  { name: 'Aqua', colors: ['#134E5E', '#71B280'], direction: 'to right', category: 'CSS' },
  { name: 'Cherry', colors: ['#EB3349', '#F45C43'], direction: 'to right', category: 'CSS' },
  { name: 'Mojito', colors: ['#48b1bf', '#06beb6'], direction: 'to right', category: 'CSS' },
  { name: 'Coffee', colors: ['#4b6cb7', '#182848'], direction: 'to bottom', category: 'CSS' },
  { name: 'Winter', colors: ['#e6dada', '#274046'], direction: 'to top', category: 'CSS' },
  { name: 'Skyline', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: 'CSS' },
  { name: 'Honey Dew', colors: ['#43C6AC', '#F8FFAE'], direction: 'to right', category: 'CSS' },
  { name: 'Kye Meh', colors: ['#83a4d4', '#b6fbff'], direction: 'to right', category: 'CSS' },
  { name: 'Kyoto', colors: ['#c21500', '#ffc500'], direction: 'to right', category: 'CSS' },
  { name: 'Metropolis', colors: ['#252233', '#ed4264'], direction: 'to right', category: 'CSS' },
  { name: 'Misty Meadow', colors: ['#215f00', '#e4e4d9'], direction: 'to right', category: 'CSS' },
  { name: 'Neuromancer', colors: ['#f953c6', '#b91d73'], direction: 'to right', category: 'CSS' },
  { name: 'Opa', colors: ['#3d7eaa', '#ffe47a'], direction: 'to right', category: 'CSS' },
  { name: 'Orca', colors: ['#44a08d', '#093637'], direction: 'to right', category: 'CSS' },
  { name: 'Paradise', colors: ['#22e1ff', '#1d8cf8'], direction: 'to top', category: 'CSS' },
  { name: 'Pastel Orange', colors: ['#ffb347', '#ffcc33'], direction: 'to right', category: 'CSS' },
  { name: 'Pinky', colors: ['#dd5e89', '#f7bb97'], direction: 'to right', category: 'CSS' },
  { name: 'Purple Paradise', colors: ['#1d2b64', '#f8cdda'], direction: 'to right', category: 'CSS' },
  { name: 'Sea Blue', colors: ['#2b5876', '#4e4376'], direction: 'to right', category: 'CSS' },
  { name: 'Stellar', colors: ['#7474bf', '#348ac7'], direction: 'to right', category: 'CSS' },
  { name: 'Under the Lake', colors: ['#0575e6', '#00f260'], direction: 'to right', category: 'CSS' },
  { name: 'Wedding Day', colors: ['#40e0d0', '#ff8c00', '#ff0080'], direction: 'to right', category: 'CSS' },
  { name: 'Deep Space', colors: ['#000046', '#1CB5E0'], direction: 'to bottom', category: 'CSS' },
  { name: 'Harvey', colors: ['#1f4037', '#99f2c8'], direction: 'to right', category: 'CSS' },
  { name: 'Amin', colors: ['#8E2DE2', '#4A00E0'], direction: 'to right', category: 'CSS' },
  { name: 'Memariani', colors: ['#aa4b6b', '#6b6b83', '#3b8d99'], direction: 'to right', category: 'CSS' },
  { name: 'Moonlit Asteroid', colors: ['#0f2027', '#203a43', '#2c5364'], direction: 'to right', category: 'CSS' },
  { name: 'Cool Sky', colors: ['#2980B9', '#6DD5FA', '#FFFFFF'], direction: 'to right', category: 'CSS' },
  { name: 'Dark Ocean', colors: ['#373B44', '#4286f4'], direction: 'to right', category: 'CSS' },
  { name: 'Evening Night', colors: ['#005C97', '#363795'], direction: 'to right', category: 'CSS' },
  { name: 'Grade Grey', colors: ['#bdc3c7', '#2c3e50'], direction: 'to right', category: 'CSS' },
  { name: 'Cool Blues', colors: ['#2193b0', '#6dd5ed'], direction: 'to right', category: 'CSS' },
  { name: 'MegaTron', colors: ['#C6FFDD', '#FBD786', '#f7797d'], direction: 'to right', category: 'CSS' },
  { name: 'Nelson', colors: ['#f2709c', '#ff9472'], direction: 'to right', category: 'CSS' },
  { name: 'Kyoto', colors: ['#c21500', '#ffc500'], direction: 'to right', category: 'CSS' },
  { name: 'Aqualicious', colors: ['#50C9C3', '#96DED1'], direction: 'to right', category: 'CSS' },
  { name: 'Moorange', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: 'CSS' },
  { name: 'Peach', colors: ['#ED4264', '#FFEDBC'], direction: 'to right', category: 'CSS' },
  { name: 'Skyline', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: 'CSS' },
  { name: 'Sea Blue', colors: ['#2b5876', '#4e4376'], direction: 'to right', category: 'CSS' },
  { name: 'Stellar', colors: ['#7474bf', '#348ac7'], direction: 'to right', category: 'CSS' },
  { name: 'Limeade', colors: ['#A1FFCE', '#FAFFD1'], direction: 'to right', category: 'CSS' },
  { name: 'Disco', colors: ['#4ECDC4', '#556270'], direction: 'to right', category: 'CSS' },
  { name: 'Dania', colors: ['#BE93C5', '#7BC6CC'], direction: 'to right', category: 'CSS' },
  { name: 'Joomla', colors: ['#1e3c72', '#2a5298'], direction: 'to right', category: 'CSS' },
  { name: 'Christmas', colors: ['#2F7336', '#AA3A38'], direction: 'to right', category: 'CSS' },
  { name: 'Minnesota Vikings', colors: ['#5614B0', '#DBD65C'], direction: 'to right', category: 'CSS' },
  { name: 'Pizeel', colors: ['#11998e', '#38ef7d'], direction: 'to right', category: 'CSS' },
  { name: 'Haerlem', colors: ['#42e695', '#3bb2b8'], direction: 'to right', category: 'CSS' },
  { name: 'Apple', colors: ['#f7ff00', '#db36a4'], direction: 'to right', category: 'CSS' },
  { name: 'Telegram', colors: ['#1c92d2', '#f2fcfe'], direction: 'to right', category: 'CSS' },
  { name: 'Haiku', colors: ['#fd746c', '#ff9068'], direction: 'to right', category: 'CSS' },
  { name: 'Neuromancer', colors: ['#f953c6', '#b91d73'], direction: 'to right', category: 'CSS' },
  { name: 'Flickr', colors: ['#ff0084', '#33001b'], direction: 'to right', category: 'CSS' },
  { name: 'Vine', colors: ['#00bf8f', '#001510'], direction: 'to right', category: 'CSS' },
  { name: 'YouTube', colors: ['#e52d27', '#b31217'], direction: 'to right', category: 'CSS' },
  { name: 'Spotify', colors: ['#1ED760', '#1DB954'], direction: 'to right', category: 'CSS' },
  { name: 'Twitch', colors: ['#6441A5', '#2a0845'], direction: 'to right', category: 'CSS' },
  { name: 'WhatsApp', colors: ['#128C7E', '#075E54'], direction: 'to right', category: 'CSS' },
  { name: 'Instagram', colors: ['#833ab4', '#fd1d1d', '#fcb045'], direction: 'to right', category: 'CSS' },
  { name: 'Messenger', colors: ['#0084ff', '#00c6ff'], direction: 'to right', category: 'CSS' },
  { name: 'Morning Glow', colors: ['#FFC3A0', '#FFAFBD'], direction: 'to right', category: '优雅' },
  { name: 'Lavender Dream', colors: ['#E2D1F9', '#B8A4FC'], direction: 'to right', category: '优雅' },
  { name: 'Rose Petal', colors: ['#FAD0C4', '#FFD1FF'], direction: 'to right', category: '优雅' },
  { name: 'Creamy Peach', colors: ['#FFF5E1', '#FFD194'], direction: 'to right', category: '优雅' },
  { name: 'Velvet Wine', colors: ['#800020', '#D433FF'], direction: 'to right', category: '优雅' },
  { name: 'Candy Floss', colors: ['#FFC3A0', '#FF6767'], direction: 'to right', category: '优雅' },
  { name: 'Golden Hour', colors: ['#FFCC33', '#FFB347'], direction: 'to right', category: '优雅' },
  { name: 'Purple Mist', colors: ['#E0C3FC', '#8EC5FC'], direction: 'to top', category: '优雅' },
  { name: 'Soft Lilac', colors: ['#F3E7E9', '#E3EEFF'], direction: 'to right', category: '优雅' },
  { name: 'Sky Blue', colors: ['#89F7FE', '#66A6FF'], direction: 'to right', category: '优雅' },
  { name: 'Spring Bud', colors: ['#D4FC79', '#96E6A1'], direction: 'to right', category: '优雅' },
  { name: 'Aqua Marine', colors: ['#84FAB0', '#8FD3F4'], direction: 'to right', category: '优雅' },
  { name: 'Misty Blue', colors: ['#E6E9F0', '#EEF1F5'], direction: 'to right', category: '优雅' },
  { name: 'Blue Horizon', colors: ['#A1C4FD', '#C2E9FB'], direction: 'to right', category: '优雅' },
  { name: 'Sunset Peach', colors: ['#FF9A9E', '#FAD0C4'], direction: 'to right', category: '优雅' },
  { name: 'Lilac Breeze', colors: ['#E2D1F9', '#B8A4FC'], direction: 'to right', category: '优雅' },
  { name: 'Electric Pink', colors: ['#FF00CC', '#333399'], direction: 'to bottom', category: '优雅' },
  { name: 'Midnight Deep', colors: ['#000000', '#434343'], direction: 'to bottom', category: '优雅' },
  { name: 'Cyan Spark', colors: ['#00FFFF', '#008080'], direction: 'to bottom', category: '优雅' },
  { name: 'Forest Night', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Depth', colors: ['#000046', '#1CB5E0'], direction: 'to bottom', category: '优雅' },
  { name: 'Cosmic Fusion', colors: ['#FF0099', '#493240'], direction: 'to right', category: '优雅' },
  { name: 'Pastel Dreams', colors: ['#F3E7E9', '#DAD4EC'], direction: 'to right', category: '优雅' },
  { name: 'Northern Lights', colors: ['#00F260', '#0575E6'], direction: 'to bottom', category: '优雅' },
  { name: 'Sunny Day', colors: ['#FFF9C4', '#FFEB3B'], direction: 'to bottom', category: '优雅' },
  { name: 'Frosty Sky', colors: ['#E0F7FA', '#B2EBF2'], direction: 'to right', category: '优雅' },
  { name: 'Golden Sand', colors: ['#FFF9C4', '#FFCC80'], direction: 'to right', category: '优雅' },
  { name: 'Purple Night', colors: ['#4A148C', '#7B1FA2'], direction: 'to bottom', category: '优雅' },
  { name: 'Silver Mist', colors: ['#E0E0E0', '#F5F5F5'], direction: 'to bottom', category: '优雅' },
  { name: 'Azure Dream', colors: ['#2196F3', '#00BCD4'], direction: 'to right', category: '优雅' },
  { name: 'Warm Sunset', colors: ['#FF5722', '#FFC107'], direction: 'to right', category: '优雅' },
  { name: 'Deep Purple', colors: ['#673AB7', '#9C27B0'], direction: 'to bottom', category: '优雅' },
  { name: 'Ghost White', colors: ['#F8F8FF', '#FFFFFF'], direction: 'to bottom', category: '优雅' },
  { name: 'Cool Mint', colors: ['#B2FEFA', '#0ED2F7'], direction: 'to right', category: '优雅' },
  { name: 'Electric Blue', colors: ['#00B4DB', '#0083B0'], direction: 'to right', category: '优雅' },
  { name: 'Soft Lavender', colors: ['#E1BEE7', '#F3E5F5'], direction: 'to right', category: '优雅' },
  { name: 'Grey Dawn', colors: ['#BDBDBD', '#E0E0E0'], direction: 'to right', category: '优雅' },
  { name: 'Royal Blue', colors: ['#243B55', '#141E30'], direction: 'to bottom', category: '优雅' },
  { name: 'Fresh Air', colors: ['#E0F2F1', '#B2DFDB'], direction: 'to bottom', category: '优雅' },
  { name: 'Candy Pink', colors: ['#F8BBD0', '#FCE4EC'], direction: 'to right', category: '优雅' },
  { name: 'Olive Grove', colors: ['#9E9D24', '#C0CA33'], direction: 'to right', category: '优雅' },
  { name: 'Dusk Sky', colors: ['#3F51B5', '#5C6BC0'], direction: 'to right', category: '优雅' },
  { name: 'Pure White', colors: ['#FFFFFF', '#ECEFF1'], direction: 'to bottom', category: '优雅' },
  { name: 'Tropical Sea', colors: ['#009688', '#4DB6AC'], direction: 'to right', category: '优雅' },
  { name: 'Pale Rose', colors: ['#FCE4EC', '#F8BBD0'], direction: 'to bottom', category: '优雅' },
  { name: 'Deep Sea Blue', colors: ['#1A237E', '#3949AB'], direction: 'to bottom', category: '优雅' },
  { name: 'Misty Grey', colors: ['#CFD8DC', '#ECEFF1'], direction: 'to right', category: '优雅' },
  { name: 'Twilight Purple', colors: ['#311B92', '#512DA8'], direction: 'to bottom', category: '优雅' },
  { name: 'Morning Dew', colors: ['#F1F8E9', '#DCEDC8'], direction: 'to right', category: '优雅' },
  { name: 'Coral Reef', colors: ['#FF8A65', '#FFAB91'], direction: 'to bottom', category: '优雅' },
  { name: 'Steel Blue', colors: ['#455A64', '#607D8B'], direction: 'to right', category: '优雅' },
  { name: 'Arctic White', colors: ['#E1F5FE', '#B3E5FC'], direction: 'to right', category: '优雅' },
  { name: 'Obsidian', colors: ['#212121', '#424242'], direction: 'to bottom', category: '优雅' },
  { name: 'Navy Depth', colors: ['#0D47A1', '#1976D2'], direction: 'to bottom', category: '优雅' },
  { name: 'Frosty Morning', colors: ['#E3F2FD', '#BBDEFB'], direction: 'to bottom', category: '优雅' },
  { name: 'Bright Sun', colors: ['#FFFDE7', '#FFF9C4'], direction: 'to right', category: '优雅' },
  { name: 'Charcoal', colors: ['#263238', '#37474F'], direction: 'to bottom', category: '优雅' },
  { name: 'Soft Teal', colors: ['#E0F2F1', '#B2DFDB'], direction: 'to right', category: '优雅' },
  { name: 'Warm Clay', colors: ['#D7CCC8', '#EFEBE9'], direction: 'to bottom', category: '优雅' },
  { name: 'Cyan Dream', colors: ['#E0F7FA', '#B2EBF2'], direction: 'to right', category: '优雅' },
  { name: 'Silk Road', colors: ['#FDFCFB', '#E2D1C3'], direction: 'to right', category: '优雅' },
  { name: 'Royal Garden', colors: ['#FFF1EB', '#ACE0F9'], direction: 'to right', category: '优雅' },
  { name: 'Night Call', colors: ['#AC92EB', '#4FC3F7', '#48CFAD', '#FFCE54', '#ED5565'], direction: 'to right', category: '优雅' },
  { name: 'Sweet Morning', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Margo', colors: ['#FF9A9E', '#FAD0C4'], direction: 'to right', category: '优雅' },
  { name: 'Clean Mirror', colors: ['#E3F2FD', '#BBDEFB'], direction: 'to right', category: '优雅' },
  { name: 'Viking', colors: ['#485563', '#29323C'], direction: 'to right', category: '优雅' },
  { name: 'Lush', colors: ['#A8E063', '#56AB2F'], direction: 'to right', category: '优雅' },
  { name: 'Reef', colors: ['#00D2FF', '#3A7BD5'], direction: 'to right', category: '优雅' },
  { name: 'Neon Life', colors: ['#B3FFAB', '#12FFF7'], direction: 'to right', category: '优雅' },
  { name: 'Magic', colors: ['#59C173', '#A17FE0', '#5D26C1'], direction: 'to right', category: '优雅' },
  { name: 'Love', colors: ['#FF0844', '#FFB199'], direction: 'to right', category: '优雅' },
  { name: 'Deep Space', colors: ['#000000', '#434343'], direction: 'to right', category: '优雅' },
  { name: 'Metropolis', colors: ['#252233', '#ED4264'], direction: 'to right', category: '优雅' },
  { name: 'Opa', colors: ['#3D7EAA', '#FFE47A'], direction: 'to right', category: '优雅' },
  { name: 'Shroom Haze', colors: ['#5C258D', '#4389A2'], direction: 'to right', category: '优雅' },
  { name: 'Kyoto', colors: ['#C21500', '#FFC500'], direction: 'to right', category: '优雅' },
  { name: 'Misty Meadow', colors: ['#215F00', '#E4E4D9'], direction: 'to right', category: '优雅' },
  { name: 'Stellar', colors: ['#7474BF', '#348AC7'], direction: 'to right', category: '优雅' },
  { name: 'Celestial', colors: ['#C33764', '#1D2671'], direction: 'to right', category: '优雅' },
  { name: 'Sunkist', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Coal', colors: ['#EB5757', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Flickr', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'Forest', colors: ['#5A3F37', '#2C7744'], direction: 'to right', category: '优雅' },
  { name: 'Tania', colors: ['#12C2E9', '#C471ED', '#F64F59'], direction: 'to right', category: '优雅' },
  { name: 'Moorange', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Aqualicious', colors: ['#50C9C3', '#96DED1'], direction: 'to right', category: '优雅' },
  { name: 'Tranquil', colors: ['#EECDA3', '#EF629F'], direction: 'to right', category: '优雅' },
  { name: 'Shifter', colors: ['#BC4E9C', '#F80759'], direction: 'to right', category: '优雅' },
  { name: 'Sun on the Horizon', colors: ['#FDC830', '#F37335'], direction: 'to right', category: '优雅' },
  { name: 'Blood Red', colors: ['#F85032', '#E73827'], direction: 'to right', category: '优雅' },
  { name: 'Sherbert', colors: ['#F79D00', '#64F38C'], direction: 'to right', category: '优雅' },
  { name: 'Firewatch', colors: ['#CB2D3E', '#EF473A'], direction: 'to right', category: '优雅' },
  { name: 'Duluth', colors: ['#666666', '#999999'], direction: 'to right', category: '优雅' },
  { name: 'Kye Meh', colors: ['#83A4D4', '#B6FBFF'], direction: 'to right', category: '优雅' },
  { name: 'Starfall', colors: ['#F0C27B', '#4B1248'], direction: 'to right', category: '优雅' },
  { name: 'Dusk', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Skyline', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Moonrise', colors: ['#DAE2F8', '#D6A4A4'], direction: 'to right', category: '优雅' },
  { name: 'Peach', colors: ['#ED4264', '#FFEDBC'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Noon to Dusk', colors: ['#FF5E62', '#FF9966'], direction: 'to right', category: '优雅' },
  { name: 'Winter', colors: ['#E6DADA', '#274046'], direction: 'to right', category: '优雅' },
  { name: 'Nelson', colors: ['#F2709C', '#FF9472'], direction: 'to right', category: '优雅' },
  { name: 'Aubergine', colors: ['#AA076B', '#61045F'], direction: 'to right', category: '优雅' },
  { name: 'Post-it', colors: ['#FFFBD5', '#B20A2C'], direction: 'to right', category: '优雅' },
  { name: 'Hemlock', colors: ['#868F96', '#596164'], direction: 'to right', category: '优雅' },
  { name: 'Slight Ocean View', colors: ['#A8CABA', '#5D4157'], direction: 'to right', category: '优雅' },
  { name: 'Joomla', colors: ['#1E3C72', '#2A5298'], direction: 'to right', category: '优雅' },
  { name: 'Christmas', colors: ['#2F7336', '#AA3A38'], direction: 'to right', category: '优雅' },
  { name: 'Minnesota Vikings', colors: ['#5614B0', '#DBD65C'], direction: 'to right', category: '优雅' },
  { name: 'Pizeel', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Haerlem', colors: ['#42E695', '#3BB2B8'], direction: 'to right', category: '优雅' },
  { name: 'Apple', colors: ['#F7FF00', '#DB36A4'], direction: 'to right', category: '优雅' },
  { name: 'Telegram', colors: ['#1C92D2', '#F2FCFE'], direction: 'to right', category: '优雅' },
  { name: 'Haiku', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Flickr', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'YouTube', colors: ['#E52D27', '#B31217'], direction: 'to right', category: '优雅' },
  { name: 'Spotify', colors: ['#1ED760', '#1DB954'], direction: 'to right', category: '优雅' },
  { name: 'Twitch', colors: ['#6441A5', '#2A0845'], direction: 'to right', category: '优雅' },
  { name: 'WhatsApp', colors: ['#128C7E', '#075E54'], direction: 'to right', category: '优雅' },
  { name: 'Instagram Original', colors: ['#833AB4', '#FD1D1D', '#FCB045'], direction: 'to right', category: '优雅' },
  { name: 'Messenger Blue', colors: ['#0084FF', '#00C6FF'], direction: 'to right', category: '优雅' },
  { name: 'Deep Space Sparkle', colors: ['#4A00E0', '#8E2DE2'], direction: 'to right', category: '优雅' },
  { name: 'Midnight City', colors: ['#232526', '#414345'], direction: 'to right', category: '优雅' },
  { name: 'Ocean View', colors: ['#2B32B2', '#1488CC'], direction: 'to right', category: '优雅' },
  { name: 'Pacific Dream', colors: ['#34E89E', '#0F3443'], direction: 'to right', category: '优雅' },
  { name: 'Venice Blue', colors: ['#085078', '#85D8CE'], direction: 'to right', category: '优雅' },
  { name: 'Bora Bora', colors: ['#2BC0E4', '#EAECC6'], direction: 'to right', category: '优雅' },
  { name: 'Electric Violet', colors: ['#4776E6', '#8E54E9'], direction: 'to right', category: '优雅' },
  { name: 'Candy', colors: ['#D3959B', '#B20A2C'], direction: 'to right', category: '优雅' },
  { name: 'Ibiza Sunset', colors: ['#EE0979', '#FF6A00'], direction: 'to right', category: '优雅' },
  { name: 'Dawn', colors: ['#F3904F', '#3B4371'], direction: 'to right', category: '优雅' },
  { name: 'Wild Apple', colors: ['#D24D57', '#F22613'], direction: 'to right', category: '优雅' },
  { name: 'Cherry Blossom', colors: ['#FBD3E9', '#BB377D'], direction: 'to right', category: '优雅' },
  { name: 'Plum Plate', colors: ['#667EEA', '#764BA2'], direction: 'to right', category: '优雅' },
  { name: 'Everlasting Sky', colors: ['#FDFBFB', '#EBEDEE'], direction: 'to right', category: '优雅' },
  { name: 'Happy Fisher', colors: ['#89F7FE', '#66A6FF'], direction: 'to right', category: '优雅' },
  { name: 'Blessing', colors: ['#FDD1D1', '#FA71CD'], direction: 'to right', category: '优雅' },
  { name: 'Milky Way', colors: ['#D5D4D0', '#D5D4D0', '#EEEEEC', '#EFEEEC', '#E9E9E7'], direction: 'to right', category: '优雅' },
  { name: 'Kindness', colors: ['#FA709A', '#FEE140'], direction: 'to right', category: '优雅' },
  { name: 'Clean Mirror', colors: ['#93A5CF', '#E4EFE9'], direction: 'to right', category: '优雅' },
  { name: 'Premium Dark', colors: ['#434343', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Mars Party', colors: ['#5F2C82', '#49A09D'], direction: 'to right', category: '优雅' },
  { name: 'New Retrowave', colors: ['#3B8D99', '#6B6B83', '#AA4B6B'], direction: 'to right', category: '优雅' },
  { name: 'Nighthawk', colors: ['#2980B9', '#2C3E50'], direction: 'to right', category: '优雅' },
  { name: 'Lush', colors: ['#56AB2F', '#A8E063'], direction: 'to right', category: '优雅' },
  { name: 'Aqualicious', colors: ['#50C9C3', '#96DED1'], direction: 'to right', category: '优雅' },
  { name: 'Sands of Time', colors: ['#FBC2EB', '#A6C1EE'], direction: 'to right', category: '优雅' },
  { name: 'Deep Blue', colors: ['#000428', '#004E92'], direction: 'to right', category: '优雅' },
  { name: 'Summer Dog', colors: ['#A8FF78', '#78FFD6'], direction: 'to right', category: '优雅' },
  { name: 'Digital Water', colors: ['#74EBD5', '#9FACE6'], direction: 'to right', category: '优雅' },
  { name: 'Orange Juice', colors: ['#FC466B', '#3F5EFB'], direction: 'to right', category: '优雅' },
  { name: 'Custard', colors: ['#EE9CA7', '#FFDDE1'], direction: 'to right', category: '优雅' },
  { name: 'Strawberry', colors: ['#FE8C00', '#F83600'], direction: 'to right', category: '优雅' },
  { name: 'Faint Worm', colors: ['#D4FC79', '#96E6A1'], direction: 'to right', category: '优雅' },
  { name: 'Fruity', colors: ['#FFB75E', '#ED8F03'], direction: 'to right', category: '优雅' },
  { name: 'Rose Water', colors: ['#E55D87', '#5FC3E4'], direction: 'to right', category: '优雅' },
  { name: 'Sea Wave', colors: ['#2E3192', '#1BFFFF'], direction: 'to right', category: '优雅' },
  { name: 'Emerald', colors: ['#348F50', '#56B4D3'], direction: 'to right', category: '优雅' },
  { name: 'Amethyst', colors: ['#9D50BB', '#6E48AA'], direction: 'to right', category: '优雅' },
  { name: 'Citrus', colors: ['#FDC830', '#F37335'], direction: 'to right', category: '优雅' },
  { name: 'Turquoise Flow', colors: ['#134E5E', '#71B280'], direction: 'to right', category: '优雅' },
  { name: 'Blue Whale', colors: ['#000046', '#1CB5E0'], direction: 'to right', category: '优雅' },
  { name: 'Red Sunset', colors: ['#355C7D', '#6C5B7B', '#C06C84'], direction: 'to right', category: '优雅' },
  { name: 'Vaporwave', colors: ['#96262C', '#4A47A3'], direction: 'to right', category: '优雅' },
  { name: 'Pink Glace', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Sleek Sky', colors: ['#2980B9', '#6DD5FA', '#FFFFFF'], direction: 'to right', category: '优雅' },
  { name: 'Pure Lust', colors: ['#333333', '#DD1818'], direction: 'to right', category: '优雅' },
  { name: 'Moorange Shine', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Viking Deep', colors: ['#485563', '#29323C'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Blue', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Reef Green', colors: ['#00D2FF', '#3A7BD5'], direction: 'to right', category: '优雅' },
  { name: 'Neon Life Glow', colors: ['#B3FFAB', '#12FFF7'], direction: 'to right', category: '优雅' },
  { name: 'Magic Night', colors: ['#59C173', '#A17FE0', '#5D26C1'], direction: 'to right', category: '优雅' },
  { name: 'Love Kiss', colors: ['#FF0844', '#FFB199'], direction: 'to right', category: '优雅' },
  { name: 'Deep Space Black', colors: ['#000000', '#434343'], direction: 'to right', category: '优雅' },
  { name: 'Metropolis Night', colors: ['#252233', '#ED4264'], direction: 'to right', category: '优雅' },
  { name: 'Opa Gold', colors: ['#3D7EAA', '#FFE47A'], direction: 'to right', category: '优雅' },
  { name: 'Shroom Haze Purple', colors: ['#5C258D', '#4389A2'], direction: 'to right', category: '优雅' },
  { name: 'Kyoto Sun', colors: ['#C21500', '#FFC500'], direction: 'to right', category: '优雅' },
  { name: 'Misty Meadow Green', colors: ['#215F00', '#E4E4D9'], direction: 'to right', category: '优雅' },
  { name: 'Stellar Blue', colors: ['#7474BF', '#348AC7'], direction: 'to right', category: '优雅' },
  { name: 'Celestial Dark', colors: ['#C33764', '#1D2671'], direction: 'to right', category: '优雅' },
  { name: 'Sunkist Orange', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Coal Fire', colors: ['#EB5757', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Pink', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Green', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'Forest Wood', colors: ['#5A3F37', '#2C7744'], direction: 'to right', category: '优雅' },
  { name: 'Tania Tri', colors: ['#12C2E9', '#C471ED', '#F64F59'], direction: 'to right', category: '优雅' },
  { name: 'Tranquil Peach', colors: ['#EECDA3', '#EF629F'], direction: 'to right', category: '优雅' },
  { name: 'Shifter Pink', colors: ['#BC4E9C', '#F80759'], direction: 'to right', category: '优雅' },
  { name: 'Sun Horizon Gold', colors: ['#FDC830', '#F37335'], direction: 'to right', category: '优雅' },
  { name: 'Blood Red Deep', colors: ['#F85032', '#E73827'], direction: 'to right', category: '优雅' },
  { name: 'Sherbert Lime', colors: ['#F79D00', '#64F38C'], direction: 'to right', category: '优雅' },
  { name: 'Firewatch Red', colors: ['#CB2D3E', '#EF473A'], direction: 'to right', category: '优雅' },
  { name: 'Duluth Grey', colors: ['#666666', '#999999'], direction: 'to right', category: '优雅' },
  { name: 'Kye Meh Sky', colors: ['#83A4D4', '#B6FBFF'], direction: 'to right', category: '优雅' },
  { name: 'Starfall Purple', colors: ['#F0C27B', '#4B1248'], direction: 'to right', category: '优雅' },
  { name: 'Dusk Orange', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Blue Deep', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Moonrise Rose', colors: ['#DAE2F8', '#D6A4A4'], direction: 'to right', category: '优雅' },
  { name: 'Peach Burst', colors: ['#ED4264', '#FFEDBC'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue Deep', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Noon Dusk Orange', colors: ['#FF5E62', '#FF9966'], direction: 'to right', category: '优雅' },
  { name: 'Winter Grey', colors: ['#E6DADA', '#274046'], direction: 'to right', category: '优雅' },
  { name: 'Nelson Pink', colors: ['#F2709C', '#FF9472'], direction: 'to right', category: '优雅' },
  { name: 'Aubergine Purple', colors: ['#AA076B', '#61045F'], direction: 'to right', category: '优雅' },
  { name: 'Post-it Red', colors: ['#FFFBD5', '#B20A2C'], direction: 'to right', category: '优雅' },
  { name: 'Hemlock Grey', colors: ['#868F96', '#596164'], direction: 'to right', category: '优雅' },
  { name: 'Slight Ocean View Mist', colors: ['#A8CABA', '#5D4157'], direction: 'to right', category: '优雅' },
  { name: 'Joomla Blue', colors: ['#1E3C72', '#2A5298'], direction: 'to right', category: '优雅' },
  { name: 'Christmas Red Green', colors: ['#2F7336', '#AA3A38'], direction: 'to right', category: '优雅' },
  { name: 'Minnesota Vikings Purple', colors: ['#5614B0', '#DBD65C'], direction: 'to right', category: '优雅' },
  { name: 'Pizeel Green', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Haerlem Blue', colors: ['#42E695', '#3BB2B8'], direction: 'to right', category: '优雅' },
  { name: 'Apple Pink', colors: ['#F7FF00', '#DB36A4'], direction: 'to right', category: '优雅' },
  { name: 'Telegram Blue', colors: ['#1C92D2', '#F2FCFE'], direction: 'to right', category: '优雅' },
  { name: 'Haiku Orange', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer Pink', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Dark', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Dark', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'YouTube Red', colors: ['#E52D27', '#B31217'], direction: 'to right', category: '优雅' },
  { name: 'Spotify Green', colors: ['#1ED760', '#1DB954'], direction: 'to right', category: '优雅' },
  { name: 'Twitch Purple', colors: ['#6441A5', '#2A0845'], direction: 'to right', category: '优雅' },
  { name: 'WhatsApp Green', colors: ['#128C7E', '#075E54'], direction: 'to right', category: '优雅' },
  { name: 'Instagram Rainbow', colors: ['#833AB4', '#FD1D1D', '#FCB045'], direction: 'to right', category: '优雅' },
  { name: 'Messenger Blue Glow', colors: ['#0084FF', '#00C6FF'], direction: 'to right', category: '优雅' },
  { name: 'Deep Space Shine', colors: ['#4A00E0', '#8E2DE2'], direction: 'to right', category: '优雅' },
  { name: 'Midnight City Dark', colors: ['#232526', '#414345'], direction: 'to right', category: '优雅' },
  { name: 'Ocean View Shine', colors: ['#2B32B2', '#1488CC'], direction: 'to right', category: '优雅' },
  { name: 'Pacific Dream Deep', colors: ['#34E89E', '#0F3443'], direction: 'to right', category: '优雅' },
  { name: 'Venice Blue Shine', colors: ['#085078', '#85D8CE'], direction: 'to right', category: '优雅' },
  { name: 'Bora Bora Shine', colors: ['#2BC0E4', '#EAECC6'], direction: 'to right', category: '优雅' },
  { name: 'Electric Violet Shine', colors: ['#4776E6', '#8E54E9'], direction: 'to right', category: '优雅' },
  { name: 'Candy Red', colors: ['#D3959B', '#B20A2C'], direction: 'to right', category: '优雅' },
  { name: 'Ibiza Sunset Glow', colors: ['#EE0979', '#FF6A00'], direction: 'to right', category: '优雅' },
  { name: 'Dawn Shine', colors: ['#F3904F', '#3B4371'], direction: 'to right', category: '优雅' },
  { name: 'Wild Apple Shine', colors: ['#D24D57', '#F22613'], direction: 'to right', category: '优雅' },
  { name: 'Cherry Blossom Shine', colors: ['#FBD3E9', '#BB377D'], direction: 'to right', category: '优雅' },
  { name: 'Plum Plate Shine', colors: ['#667EEA', '#764BA2'], direction: 'to right', category: '优雅' },
  { name: 'Everlasting Sky Shine', colors: ['#FDFBFB', '#EBEDEE'], direction: 'to right', category: '优雅' },
  { name: 'Happy Fisher Shine', colors: ['#89F7FE', '#66A6FF'], direction: 'to right', category: '优雅' },
  { name: 'Blessing Shine', colors: ['#FDD1D1', '#FA71CD'], direction: 'to right', category: '优雅' },
  { name: 'Milky Way Shine', colors: ['#D5D4D0', '#D5D4D0', '#EEEEEC', '#EFEEEC', '#E9E9E7'], direction: 'to right', category: '优雅' },
  { name: 'Kindness Shine', colors: ['#FA709A', '#FEE140'], direction: 'to right', category: '优雅' },
  { name: 'Clean Mirror Shine', colors: ['#93A5CF', '#E4EFE9'], direction: 'to right', category: '优雅' },
  { name: 'Premium Dark Shine', colors: ['#434343', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Mars Party Shine', colors: ['#5F2C82', '#49A09D'], direction: 'to right', category: '优雅' },
  { name: 'New Retrowave Shine', colors: ['#3B8D99', '#6B6B83', '#AA4B6B'], direction: 'to right', category: '优雅' },
  { name: 'Nighthawk Shine', colors: ['#2980B9', '#2C3E50'], direction: 'to right', category: '优雅' },
  { name: 'Lush Shine', colors: ['#56AB2F', '#A8E063'], direction: 'to right', category: '优雅' },
  { name: 'Aqualicious Shine', colors: ['#50C9C3', '#96DED1'], direction: 'to right', category: '优雅' },
  { name: 'Sands of Time Shine', colors: ['#FBC2EB', '#A6C1EE'], direction: 'to right', category: '优雅' },
  { name: 'Deep Blue Shine', colors: ['#000428', '#004E92'], direction: 'to right', category: '优雅' },
  { name: 'Summer Dog Shine', colors: ['#A8FF78', '#78FFD6'], direction: 'to right', category: '优雅' },
  { name: 'Digital Water Shine', colors: ['#74EBD5', '#9FACE6'], direction: 'to right', category: '优雅' },
  { name: 'Orange Juice Shine', colors: ['#FC466B', '#3F5EFB'], direction: 'to right', category: '优雅' },
  { name: 'Custard Shine', colors: ['#EE9CA7', '#FFDDE1'], direction: 'to right', category: '优雅' },
  { name: 'Strawberry Shine', colors: ['#FE8C00', '#F83600'], direction: 'to right', category: '优雅' },
  { name: 'Faint Worm Shine', colors: ['#D4FC79', '#96E6A1'], direction: 'to right', category: '优雅' },
  { name: 'Fruity Shine', colors: ['#FFB75E', '#ED8F03'], direction: 'to right', category: '优雅' },
  { name: 'Rose Water Shine', colors: ['#E55D87', '#5FC3E4'], direction: 'to right', category: '优雅' },
  { name: 'Sea Wave Shine', colors: ['#2E3192', '#1BFFFF'], direction: 'to right', category: '优雅' },
  { name: 'Emerald Shine', colors: ['#348F50', '#56B4D3'], direction: 'to right', category: '优雅' },
  { name: 'Amethyst Shine', colors: ['#9D50BB', '#6E48AA'], direction: 'to right', category: '优雅' },
  { name: 'Citrus Shine', colors: ['#FDC830', '#F37335'], direction: 'to right', category: '优雅' },
  { name: 'Turquoise Flow Shine', colors: ['#134E5E', '#71B280'], direction: 'to right', category: '优雅' },
  { name: 'Blue Whale Shine', colors: ['#000046', '#1CB5E0'], direction: 'to right', category: '优雅' },
  { name: 'Red Sunset Shine', colors: ['#355C7D', '#6C5B7B', '#C06C84'], direction: 'to right', category: '优雅' },
  { name: 'Vaporwave Shine', colors: ['#96262C', '#4A47A3'], direction: 'to right', category: '优雅' },
  { name: 'Pink Glace Shine', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Sleek Sky Shine', colors: ['#2980B9', '#6DD5FA', '#FFFFFF'], direction: 'to right', category: '优雅' },
  { name: 'Royal Velvet', colors: ['#120136', '#035aa6'], direction: 'to bottom', category: '优雅' },
  { name: 'Silk Lavender', colors: ['#c471ed', '#f64f59'], direction: 'to right', category: '优雅' },
  { name: 'Golden Mist', colors: ['#e65c00', '#F9D423'], direction: 'to right', category: '优雅' },
  { name: 'Morning Frost', colors: ['#00d2ff', '#928dab'], direction: 'to right', category: '优雅' },
  { name: 'Copper Glow', colors: ['#b79891', '#94716b'], direction: 'to right', category: '优雅' },
  { name: 'Jade Garden', colors: ['#9be15d', '#00e3ae'], direction: 'to top', category: '优雅' },
  { name: 'Indigo Dream', colors: ['#360033', '#0b8793'], direction: 'to right', category: '优雅' },
  { name: 'Rose Quartz', colors: ['#ffafbd', '#ffc3a0'], direction: 'to right', category: '优雅' },
  { name: 'Sapphire Depth', colors: ['#021B79', '#0575E6'], direction: 'to bottom', category: '优雅' },
  { name: 'Amber Horizon', colors: ['#FF8008', '#FFC837'], direction: 'to right', category: '优雅' },
  { name: 'Platinum Silver', colors: ['#757F9A', '#D7DDE8'], direction: 'to right', category: '优雅' },
  { name: 'Ruby Wine', colors: ['#4b1248', '#f0c27b'], direction: 'to right', category: '优雅' },
  { name: 'Forest Spirit', colors: ['#11998e', '#38ef7d'], direction: 'to bottom', category: '优雅' },
  { name: 'Coral Kiss', colors: ['#ff9966', '#ff5e62'], direction: 'to right', category: '优雅' },
  { name: 'Azure Shine', colors: ['#2196f3', '#f44336'], direction: 'to right', category: '优雅' },
  { name: 'Violet Ray', colors: ['#8e2de2', '#4a00e0'], direction: 'to top', category: '优雅' },
  { name: 'Opal Essence', colors: ['#E0EAFC', '#CFDEF3'], direction: 'to right', category: '优雅' },
  { name: 'Midnight Purple', colors: ['#200122', '#6f0000'], direction: 'to bottom', category: '优雅' },
  { name: 'Tropical Paradise', colors: ['#00F260', '#0575E6'], direction: 'to top', category: '优雅' },
  { name: 'Desert Sun', colors: ['#f46b45', '#eea849'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Mist', colors: ['#1e3c72', '#2a5298'], direction: 'to top', category: '优雅' },
  { name: 'Plum Dream', colors: ['#cc2b5e', '#753a88'], direction: 'to right', category: '优雅' },
  { name: 'Emerald Isle', colors: ['#00b09b', '#96c93d'], direction: 'to right', category: '优雅' },
  { name: 'Golden Sands', colors: ['#F2994A', '#F2C94C'], direction: 'to top', category: '优雅' },
  { name: 'Pizeel', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Haerlem', colors: ['#42E695', '#3BB2B8'], direction: 'to right', category: '优雅' },
  { name: 'Apple', colors: ['#F7FF00', '#DB36A4'], direction: 'to right', category: '优雅' },
  { name: 'Telegram', colors: ['#1C92D2', '#F2FCFE'], direction: 'to right', category: '优雅' },
  { name: 'Haiku', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Flickr', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'YouTube', colors: ['#E52D27', '#B31217'], direction: 'to right', category: '优雅' },
  { name: 'Spotify', colors: ['#1ED760', '#1DB954'], direction: 'to right', category: '优雅' },
  { name: 'Twitch', colors: ['#6441A5', '#2A0845'], direction: 'to right', category: '优雅' },
  { name: 'WhatsApp', colors: ['#128C7E', '#075E54'], direction: 'to right', category: '优雅' },
  { name: 'Instagram', colors: ['#833AB4', '#FD1D1D', '#FCB045'], direction: 'to right', category: '优雅' },
  { name: 'Messenger', colors: ['#0084FF', '#00C6FF'], direction: 'to right', category: '优雅' },
  { name: 'Rose', colors: ['#F4C4F3', '#FC67FA'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue Deep', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Horizon', colors: ['#003973', '#E5E5BE'], direction: 'to right', category: '优雅' },
  { name: 'Deep Purple Night', colors: ['#673AB7', '#512DA8'], direction: 'to right', category: '优雅' },
  { name: 'Oceanic', colors: ['#001111', '#004444'], direction: 'to right', category: '优雅' },
  { name: 'Velvet', colors: ['#220000', '#440000'], direction: 'to right', category: '优雅' },
  { name: 'Midnight', colors: ['#020202', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Ghostly', colors: ['#F8F8FF', '#FFFFFF'], direction: 'to right', category: '优雅' },
  { name: 'Sky Spark', colors: ['#E1F5FE', '#03A9F4'], direction: 'to right', category: '优雅' },
  { name: 'Peach Sorbet', colors: ['#FFE0B2', '#FF7043'], direction: 'to right', category: '优雅' },
  { name: 'Spring Breeze', colors: ['#F1F8E9', '#8BC34A'], direction: 'to right', category: '优雅' },
  { name: 'Aqua Mint', colors: ['#E0F2F1', '#009688'], direction: 'to right', category: '优雅' },
  { name: 'Pink Lemonade', colors: ['#FCE4EC', '#F06292'], direction: 'to right', category: '优雅' },
  { name: 'Morning Mist', colors: ['#F3E5F5', '#BA68C8'], direction: 'to right', category: '优雅' },
  { name: 'Sunny Meadow', colors: ['#FFFDE7', '#CDDC39'], direction: 'to right', category: '优雅' },
  { name: 'Blue Lagoon Deep', colors: ['#E0F7FA', '#00BCD4'], direction: 'to right', category: '优雅' },
  { name: 'Sweet Peach', colors: ['#FFF3E0', '#FFB74D'], direction: 'to right', category: '优雅' },
  { name: 'Cool Breeze', colors: ['#E8EAF6', '#5C6BC0'], direction: 'to right', category: '优雅' },
  { name: 'Green Tea', colors: ['#E8F5E9', '#4CAF50'], direction: 'to right', category: '优雅' },
  { name: 'Rose Petal Deep', colors: ['#F8BBD0', '#E91E63'], direction: 'to right', category: '优雅' },
  { name: 'Lavender Field', colors: ['#EDE7F6', '#673AB7'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Pearl', colors: ['#B2EBF2', '#0097A7'], direction: 'to right', category: '优雅' },
  { name: 'Summer Glow', colors: ['#FFF9C4', '#FFEB3B'], direction: 'to right', category: '优雅' },
  { name: 'Mint Leaf', colors: ['#C8E6C9', '#2E7D32'], direction: 'to right', category: '优雅' },
  { name: 'Soft Sky', colors: ['#BBDEFB', '#1976D2'], direction: 'to right', category: '优雅' },
  { name: 'Peach Blossom', colors: ['#FFE0B2', '#FB8C00'], direction: 'to right', category: '优雅' },
  { name: 'Fresh Air Deep', colors: ['#B2DFDB', '#00796B'], direction: 'to right', category: '优雅' },
  { name: 'Pink Rose', colors: ['#FCE4EC', '#D81B60'], direction: 'to right', category: '优雅' },
  { name: 'Lilac Dream', colors: ['#D1C4E9', '#512DA8'], direction: 'to right', category: '优雅' },
  { name: 'Aqua Marine Deep', colors: ['#B2EBF2', '#00ACC1'], direction: 'to right', category: '优雅' },
  { name: 'Sunny Day Deep', colors: ['#FFF9C4', '#FBC02D'], direction: 'to right', category: '优雅' },
  { name: 'Silver Dream', colors: ['#BDBDBD', '#E0E0E0'], direction: 'to right', category: '优雅' },
  { name: 'Golden Night', colors: ['#FFCC33', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Royal Velvet', colors: ['#673AB7', '#E91E63'], direction: 'to right', category: '优雅' },
  { name: 'Emerald Sea', colors: ['#009688', '#8BC34A'], direction: 'to right', category: '优雅' },
  { name: 'Coral Reef Deep', colors: ['#FF8A65', '#FF5722'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Deep', colors: ['#03A9F4', '#3F51B5'], direction: 'to right', category: '优雅' },
  { name: 'Amber Glow', colors: ['#FFC107', '#FF8F00'], direction: 'to right', category: '优雅' },
  { name: 'Grey Dawn Deep', colors: ['#9E9E9E', '#616161'], direction: 'to right', category: '优雅' },
  { name: 'Sunset Deep', colors: ['#F44336', '#FF9800'], direction: 'to right', category: '优雅' },
  { name: 'Forest Deep', colors: ['#4CAF50', '#1B5E20'], direction: 'to right', category: '优雅' },
  { name: 'Blue Depth', colors: ['#2196F3', '#0D47A1'], direction: 'to right', category: '优雅' },
  { name: 'Pink Depth', colors: ['#E91E63', '#880E4F'], direction: 'to right', category: '优雅' },
  { name: 'Purple Depth', colors: ['#9C27B0', '#4A148C'], direction: 'to right', category: '优雅' },
  { name: 'Teal Depth', colors: ['#009688', '#004D40'], direction: 'to right', category: '优雅' },
  { name: 'Orange Depth', colors: ['#FF9800', '#E65100'], direction: 'to right', category: '优雅' },
  { name: 'Green Depth', colors: ['#4CAF50', '#1B5E20'], direction: 'to right', category: '优雅' },
  { name: 'Indigo Depth', colors: ['#3F51B5', '#1A237E'], direction: 'to right', category: '优雅' },
  { name: 'Deep Sea Blue', colors: ['#1A237E', '#3949AB'], direction: 'to bottom', category: '优雅' },
  { name: 'Misty Grey', colors: ['#CFD8DC', '#ECEFF1'], direction: 'to right', category: '优雅' },
  { name: 'Twilight Purple Deep', colors: ['#311B92', '#512DA8'], direction: 'to bottom', category: '优雅' },
  { name: 'Morning Dew Deep', colors: ['#F1F8E9', '#DCEDC8'], direction: 'to right', category: '优雅' },
  { name: 'Coral Reef', colors: ['#FF8A65', '#FFAB91'], direction: 'to bottom', category: '优雅' },
  { name: 'Steel Blue Deep', colors: ['#455A64', '#607D8B'], direction: 'to right', category: '优雅' },
  { name: 'Arctic White Deep', colors: ['#E1F5FE', '#B3E5FC'], direction: 'to right', category: '优雅' },
  { name: 'Obsidian Deep', colors: ['#212121', '#424242'], direction: 'to bottom', category: '优雅' },
  { name: 'Navy Depth Deep', colors: ['#0D47A1', '#1976D2'], direction: 'to bottom', category: '优雅' },
  { name: 'Frosty Morning Deep', colors: ['#E3F2FD', '#BBDEFB'], direction: 'to bottom', category: '优雅' },
  { name: 'Bright Sun Deep', colors: ['#FFFDE7', '#FFF9C4'], direction: 'to right', category: '优雅' },
  { name: 'Charcoal Deep', colors: ['#263238', '#37474F'], direction: 'to bottom', category: '优雅' },
  { name: 'Soft Teal Deep', colors: ['#E0F2F1', '#B2DFDB'], direction: 'to right', category: '优雅' },
  { name: 'Warm Clay Deep', colors: ['#D7CCC8', '#EFEBE9'], direction: 'to bottom', category: '优雅' },
  { name: 'Cyan Dream Deep', colors: ['#E0F7FA', '#B2EBF2'], direction: 'to right', category: '优雅' },
  { name: 'Azure Dream Deep', colors: ['#2196F3', '#00BCD4'], direction: 'to right', category: '优雅' },
  { name: 'Warm Sunset Deep', colors: ['#FF5722', '#FFC107'], direction: 'to right', category: '优雅' },
  { name: 'Deep Purple Deep', colors: ['#673AB7', '#9C27B0'], direction: 'to bottom', category: '优雅' },
  { name: 'Ghost White Deep', colors: ['#F8F8FF', '#FFFFFF'], direction: 'to bottom', category: '优雅' },
  { name: 'Cool Mint Deep', colors: ['#B2FEFA', '#0ED2F7'], direction: 'to right', category: '优雅' },
  { name: 'Electric Blue Deep', colors: ['#00B4DB', '#0083B0'], direction: 'to right', category: '优雅' },
  { name: 'Soft Lavender Deep', colors: ['#E1BEE7', '#F3E5F5'], direction: 'to right', category: '优雅' },
  { name: 'Grey Dawn Deepest', colors: ['#BDBDBD', '#E0E0E0'], direction: 'to right', category: '优雅' },
  { name: 'Royal Blue Deep', colors: ['#243B55', '#141E30'], direction: 'to bottom', category: '优雅' },
  { name: 'Fresh Air Deepest', colors: ['#E0F2F1', '#B2DFDB'], direction: 'to bottom', category: '优雅' },
  { name: 'Candy Pink Deep', colors: ['#F8BBD0', '#FCE4EC'], direction: 'to right', category: '优雅' },
  { name: 'Olive Grove Deep', colors: ['#9E9D24', '#C0CA33'], direction: 'to right', category: '优雅' },
  { name: 'Dusk Sky Deep', colors: ['#3F51B5', '#5C6BC0'], direction: 'to right', category: '优雅' },
  { name: 'Pure White Deep', colors: ['#FFFFFF', '#ECEFF1'], direction: 'to bottom', category: '优雅' },
  { name: 'Tropical Sea Deep', colors: ['#009688', '#4DB6AC'], direction: 'to right', category: '优雅' },
  { name: 'Pale Rose Deep', colors: ['#FCE4EC', '#F8BBD0'], direction: 'to bottom', category: '优雅' },
  { name: 'Golden Hour Deep', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Silver Dream Deep', colors: ['#C0C0C0', '#808080'], direction: 'to right', category: '优雅' },
  { name: 'Midnight Deepest', colors: ['#232526', '#414345'], direction: 'to right', category: '优雅' },
  { name: 'Forest Green Deep', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Blue Deep', colors: ['#2B32B2', '#1488CC'], direction: 'to right', category: '优雅' },
  { name: 'Sunset Orange Deep', colors: ['#FF4B1F', '#1FDDFF'], direction: 'to right', category: '优雅' },
  { name: 'Purple Bliss Deep', colors: ['#360033', '#0B8793'], direction: 'to right', category: '优雅' },
  { name: 'Sky Sparkle Deep', colors: ['#159957', '#155799'], direction: 'to right', category: '优雅' },
  { name: 'Fresh Morning Deep', colors: ['#00D2FF', '#928DAB'], direction: 'to right', category: '优雅' },
  { name: 'Candy Apple Deep', colors: ['#EB3349', '#F45C43'], direction: 'to right', category: '优雅' },
  { name: 'Emerald Night Deep', colors: ['#02AAB0', '#00CDAC'], direction: 'to right', category: '优雅' },
  { name: 'Sunny Day Deepest', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Aqua Marine Deepest', colors: ['#2193B0', '#6DD5ED'], direction: 'to right', category: '优雅' },
  { name: 'Pink Rose Deep', colors: ['#EE0979', '#FF6A00'], direction: 'to right', category: '优雅' },
  { name: 'Lavender Breeze Deep', colors: ['#4568DC', '#B06AB3'], direction: 'to right', category: '优雅' },
  { name: 'Morning Mist Deep', colors: ['#43C6AC', '#191654'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Depth Deep', colors: ['#000046', '#1CB5E0'], direction: 'to right', category: '优雅' },
  { name: 'Royal Garden Deep', colors: ['#ED213A', '#93291E'], direction: 'to right', category: '优雅' },
  { name: 'Viking Deep', colors: ['#2C3E50', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Pure Sky Deep', colors: ['#7B4397', '#DC2430'], direction: 'to right', category: '优雅' },
  { name: 'Mint Green Deep', colors: ['#00B09B', '#96C93D'], direction: 'to right', category: '优雅' },
  { name: 'Gold Dust Deep', colors: ['#D4145A', '#FBB03B'], direction: 'to right', category: '优雅' },
  { name: 'Soft Purple Deep', colors: ['#662D8C', '#ED1E79'], direction: 'to right', category: '优雅' },
  { name: 'Aqua Blue Deep', colors: ['#00A8C5', '#FFFF7E'], direction: 'to right', category: '优雅' },
  { name: 'Sunset Glow Deep', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Rose Water Deep', colors: ['#E55D87', '#5FC3E4'], direction: 'to right', category: '优雅' },
  { name: 'Deep Purple Bliss', colors: ['#A18CD1', '#FBC2EB'], direction: 'to right', category: '优雅' },
  { name: 'Soft Green Deep', colors: ['#84FAB0', '#8FD3F4'], direction: 'to right', category: '优雅' },
  { name: 'Candy Pink Deepest', colors: ['#FF9A9E', '#FAD0C4'], direction: 'to right', category: '优雅' },
  { name: 'Blue Horizon Deep', colors: ['#A1C4FD', '#C2E9FB'], direction: 'to right', category: '优雅' },
  { name: 'Spring Bud Deep', colors: ['#D4FC79', '#96E6A1'], direction: 'to right', category: '优雅' },
  { name: 'Sky Blue Deep', colors: ['#89F7FE', '#66A6FF'], direction: 'to right', category: '优雅' },
  { name: 'Lilac Breeze Deepest', colors: ['#E2D1F9', '#B8A4FC'], direction: 'to right', category: '优雅' },
  { name: 'Electric Pink Deep', colors: ['#FF00CC', '#333399'], direction: 'to right', category: '优雅' },
  { name: 'Midnight Deepest Night', colors: ['#000000', '#434343'], direction: 'to right', category: '优雅' },
  { name: 'Cyan Spark Deep', colors: ['#00FFFF', '#008080'], direction: 'to right', category: '优雅' },
  { name: 'Northern Lights Deep', colors: ['#00F260', '#0575E6'], direction: 'to right', category: '优雅' },
  { name: 'Cosmic Fusion Deep', colors: ['#FF0099', '#493240'], direction: 'to right', category: '优雅' },
  { name: 'Azure Dream Deepest', colors: ['#2196F3', '#00BCD4'], direction: 'to right', category: '优雅' },
  { name: 'Honey Dew Deep', colors: ['#43C6AC', '#F8FFAE'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Deepest', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Kye Meh Deep', colors: ['#83A4D4', '#B6FBFF'], direction: 'to right', category: '优雅' },
  { name: 'Metropolis Deep', colors: ['#252233', '#ED4264'], direction: 'to right', category: '优雅' },
  { name: 'Orca Deep', colors: ['#44A08D', '#093637'], direction: 'to right', category: '优雅' },
  { name: 'Paradise Deep', colors: ['#22E1FF', '#1D8CF8'], direction: 'to right', category: '优雅' },
  { name: 'Pastel Orange Deep', colors: ['#FFB347', '#FFCC33'], direction: 'to right', category: '优雅' },
  { name: 'Purple Paradise Deep', colors: ['#1D2B64', '#F8CDDA'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue Deepest', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Stellar Deep', colors: ['#7474BF', '#348AC7'], direction: 'to right', category: '优雅' },
  { name: 'Wedding Day Deep', colors: ['#40E0D0', '#FF8C00', '#FF0080'], direction: 'to right', category: '优雅' },
  { name: 'Indigo Night Deep', colors: ['#6366F1', '#A855F7'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Breeze Deep', colors: ['#0EA5E9', '#22D3EE'], direction: 'to right', category: '优雅' },
  { name: 'Sunset Glow Deepest', colors: ['#F43F5E', '#FBBF24'], direction: 'to right', category: '优雅' },
  { name: 'Forest Mist Deep', colors: ['#10B981', '#34D399'], direction: 'to right', category: '优雅' },
  { name: 'Royal Purple Deepest', colors: ['#7C3AED', '#DB2777'], direction: 'to right', category: '优雅' },
  { name: 'Morning Sky Deep', colors: ['#38BDF8', '#818CF8'], direction: 'to right', category: '优雅' },
  { name: 'Lush Green Deep', colors: ['#22C55E', '#10B981'], direction: 'to right', category: '优雅' },
  { name: 'Burning Orange Deep', colors: ['#F97316', '#EF4444'], direction: 'to right', category: '优雅' },
  { name: 'Slate Gray Deep', colors: ['#475569', '#1E293B'], direction: 'to right', category: '优雅' },
  { name: 'Mango Deep', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Mint Deep', colors: ['#00FF87', '#60EFFF'], direction: 'to right', category: '优雅' },
  { name: 'Vibrant Blue Deep', colors: ['#0575E6', '#021B79'], direction: 'to right', category: '优雅' },
  { name: 'Strawberry Deep', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Frost Deep', colors: ['#000428', '#004E92'], direction: 'to right', category: '优雅' },
  { name: 'Evening Sunshine Deep', colors: ['#B92B27', '#1565C0'], direction: 'to right', category: '优雅' },
  { name: 'Aqua Deep', colors: ['#134E5E', '#71B280'], direction: 'to right', category: '优雅' },
  { name: 'Cherry Deep', colors: ['#EB3349', '#F45C43'], direction: 'to right', category: '优雅' },
  { name: 'Mojito Deep', colors: ['#48B1BF', '#06BEB6'], direction: 'to right', category: '优雅' },
  { name: 'Coffee Deep', colors: ['#4B6CB7', '#182848'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Deepest Night', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Kyoto Deep', colors: ['#C21500', '#FFC500'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer Deep', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Under the Lake Deep', colors: ['#0575E6', '#00F260'], direction: 'to right', category: '优雅' },
  { name: 'Elegant Gold', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Deep Ocean Blue', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Royal Velvet Deep', colors: ['#AA076B', '#61045F'], direction: 'to right', category: '优雅' },
  { name: 'Midnight Spark', colors: ['#232526', '#414345'], direction: 'to right', category: '优雅' },
  { name: 'Golden Hour Shine', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Pure Sky', colors: ['#7B4397', '#DC2430'], direction: 'to right', category: '优雅' },
  { name: 'Emerald Night', colors: ['#02AAB0', '#00CDAC'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Depth Shine', colors: ['#000046', '#1CB5E0'], direction: 'to right', category: '优雅' },
  { name: 'Sweet Morning Shine', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Margo Shine', colors: ['#FF9A9E', '#FAD0C4'], direction: 'to right', category: '优雅' },
  { name: 'Viking Shine', colors: ['#2C3E50', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Lush Shine', colors: ['#A8E063', '#56AB2F'], direction: 'to right', category: '优雅' },
  { name: 'Reef Shine', colors: ['#00D2FF', '#3A7BD5'], direction: 'to right', category: '优雅' },
  { name: 'Neon Life Shine', colors: ['#B3FFAB', '#12FFF7'], direction: 'to right', category: '优雅' },
  { name: 'Magic Shine', colors: ['#59C173', '#A17FE0', '#5D26C1'], direction: 'to right', category: '优雅' },
  { name: 'Love Shine', colors: ['#FF0844', '#FFB199'], direction: 'to right', category: '优雅' },
  { name: 'Deep Space Shine', colors: ['#000000', '#434343'], direction: 'to right', category: '优雅' },
  { name: 'Metropolis Shine', colors: ['#252233', '#ED4264'], direction: 'to right', category: '优雅' },
  { name: 'Opa Shine', colors: ['#3D7EAA', '#FFE47A'], direction: 'to right', category: '优雅' },
  { name: 'Shroom Haze Shine', colors: ['#5C258D', '#4389A2'], direction: 'to right', category: '优雅' },
  { name: 'Kyoto Shine', colors: ['#C21500', '#FFC500'], direction: 'to right', category: '优雅' },
  { name: 'Misty Meadow Shine', colors: ['#215F00', '#E4E4D9'], direction: 'to right', category: '优雅' },
  { name: 'Stellar Shine', colors: ['#7474BF', '#348AC7'], direction: 'to right', category: '优雅' },
  { name: 'Celestial Shine', colors: ['#C33764', '#1D2671'], direction: 'to right', category: '优雅' },
  { name: 'Sunkist Shine', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Coal Shine', colors: ['#EB5757', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Shine', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Shine', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'Forest Shine', colors: ['#5A3F37', '#2C7744'], direction: 'to right', category: '优雅' },
  { name: 'Tania Shine', colors: ['#12C2E9', '#C471ED', '#F64F59'], direction: 'to right', category: '优雅' },
  { name: 'Moorange Shine', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Aqualicious Shine', colors: ['#50C9C3', '#96DED1'], direction: 'to right', category: '优雅' },
  { name: 'Tranquil Shine', colors: ['#EECDA3', '#EF629F'], direction: 'to right', category: '优雅' },
  { name: 'Shifter Shine', colors: ['#BC4E9C', '#F80759'], direction: 'to right', category: '优雅' },
  { name: 'Sun Horizon Shine', colors: ['#FDC830', '#F37335'], direction: 'to right', category: '优雅' },
  { name: 'Blood Red Shine', colors: ['#F85032', '#E73827'], direction: 'to right', category: '优雅' },
  { name: 'Sherbert Shine', colors: ['#F79D00', '#64F38C'], direction: 'to right', category: '优雅' },
  { name: 'Firewatch Shine', colors: ['#CB2D3E', '#EF473A'], direction: 'to right', category: '优雅' },
  { name: 'Duluth Shine', colors: ['#666666', '#999999'], direction: 'to right', category: '优雅' },
  { name: 'Kye Meh Shine', colors: ['#83A4D4', '#B6FBFF'], direction: 'to right', category: '优雅' },
  { name: 'Starfall Shine', colors: ['#F0C27B', '#4B1248'], direction: 'to right', category: '优雅' },
  { name: 'Dusk Shine', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Shine', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Moonrise Shine', colors: ['#DAE2F8', '#D6A4A4'], direction: 'to right', category: '优雅' },
  { name: 'Peach Shine', colors: ['#ED4264', '#FFEDBC'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue Shine', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Noon Dusk Shine', colors: ['#FF5E62', '#FF9966'], direction: 'to right', category: '优雅' },
  { name: 'Winter Shine', colors: ['#E6DADA', '#274046'], direction: 'to right', category: '优雅' },
  { name: 'Nelson Shine', colors: ['#F2709C', '#FF9472'], direction: 'to right', category: '优雅' },
  { name: 'Aubergine Shine', colors: ['#AA076B', '#61045F'], direction: 'to right', category: '优雅' },
  { name: 'Post-it Shine', colors: ['#FFFBD5', '#B20A2C'], direction: 'to right', category: '优雅' },
  { name: 'Hemlock Shine', colors: ['#868F96', '#596164'], direction: 'to right', category: '优雅' },
  { name: 'Ocean View Shine', colors: ['#A8CABA', '#5D4157'], direction: 'to right', category: '优雅' },
  { name: 'Joomla Shine', colors: ['#1E3C72', '#2A5298'], direction: 'to right', category: '优雅' },
  { name: 'Christmas Shine', colors: ['#2F7336', '#AA3A38'], direction: 'to right', category: '优雅' },
  { name: 'Minnesota Vikings Shine', colors: ['#5614B0', '#DBD65C'], direction: 'to right', category: '优雅' },
  { name: 'Pizeel Shine', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Haerlem Shine', colors: ['#42E695', '#3BB2B8'], direction: 'to right', category: '优雅' },
  { name: 'Apple Shine', colors: ['#F7FF00', '#DB36A4'], direction: 'to right', category: '优雅' },
  { name: 'Telegram Shine', colors: ['#1C92D2', '#F2FCFE'], direction: 'to right', category: '优雅' },
  { name: 'Haiku Shine', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer Shine', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Shine Night', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Shine Night', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'YouTube Shine', colors: ['#E52D27', '#B31217'], direction: 'to right', category: '优雅' },
  { name: 'Spotify Shine', colors: ['#1ED760', '#1DB954'], direction: 'to right', category: '优雅' },
  { name: 'Twitch Shine', colors: ['#6441A5', '#2A0845'], direction: 'to right', category: '优雅' },
  { name: 'WhatsApp Shine', colors: ['#128C7E', '#075E54'], direction: 'to right', category: '优雅' },
  { name: 'Instagram Shine', colors: ['#833AB4', '#FD1D1D', '#FCB045'], direction: 'to right', category: '优雅' },
  { name: 'Messenger Shine', colors: ['#0084FF', '#00C6FF'], direction: 'to right', category: '优雅' },
  { name: 'Silk Road Deep', colors: ['#FDFCFB', '#E2D1C3'], direction: 'to right', category: '优雅' },
  { name: 'Royal Garden Deepest', colors: ['#FFF1EB', '#ACE0F9'], direction: 'to right', category: '优雅' },
  { name: 'Sweet Morning Deepest', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Margo Deepest', colors: ['#FF9A9E', '#FAD0C4'], direction: 'to right', category: '优雅' },
  { name: 'Clean Mirror Deep', colors: ['#E3F2FD', '#BBDEFB'], direction: 'to right', category: '优雅' },
  { name: 'Viking Deepest', colors: ['#485563', '#29323C'], direction: 'to right', category: '优雅' },
  { name: 'Lush Deepest', colors: ['#A8E063', '#56AB2F'], direction: 'to right', category: '优雅' },
  { name: 'Reef Deepest', colors: ['#00D2FF', '#3A7BD5'], direction: 'to right', category: '优雅' },
  { name: 'Neon Life Deepest', colors: ['#B3FFAB', '#12FFF7'], direction: 'to right', category: '优雅' },
  { name: 'Love Deepest', colors: ['#FF0844', '#FFB199'], direction: 'to right', category: '优雅' },
  { name: 'Deep Space Deepest', colors: ['#000000', '#434343'], direction: 'to right', category: '优雅' },
  { name: 'Metropolis Deepest', colors: ['#252233', '#ED4264'], direction: 'to right', category: '优雅' },
  { name: 'Opa Deepest', colors: ['#3D7EAA', '#FFE47A'], direction: 'to right', category: '优雅' },
  { name: 'Shroom Haze Deepest', colors: ['#5C258D', '#4389A2'], direction: 'to right', category: '优雅' },
  { name: 'Kyoto Deepest', colors: ['#C21500', '#FFC500'], direction: 'to right', category: '优雅' },
  { name: 'Misty Meadow Deepest', colors: ['#215F00', '#E4E4D9'], direction: 'to right', category: '优雅' },
  { name: 'Stellar Deepest', colors: ['#7474BF', '#348AC7'], direction: 'to right', category: '优雅' },
  { name: 'Celestial Deepest', colors: ['#C33764', '#1D2671'], direction: 'to right', category: '优雅' },
  { name: 'Sunkist Deepest', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Coal Deepest', colors: ['#EB5757', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Deepest', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Deepest', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'Forest Deepest', colors: ['#5A3F37', '#2C7744'], direction: 'to right', category: '优雅' },
  { name: 'Tania Deepest', colors: ['#12C2E9', '#C471ED', '#F64F59'], direction: 'to right', category: '优雅' },
  { name: 'Moorange Deepest', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Aqualicious Deepest', colors: ['#50C9C3', '#96DED1'], direction: 'to right', category: '优雅' },
  { name: 'Tranquil Deepest', colors: ['#EECDA3', '#EF629F'], direction: 'to right', category: '优雅' },
  { name: 'Shifter Deepest', colors: ['#BC4E9C', '#F80759'], direction: 'to right', category: '优雅' },
  { name: 'Sun Horizon Deepest', colors: ['#FDC830', '#F37335'], direction: 'to right', category: '优雅' },
  { name: 'Blood Red Deepest', colors: ['#F85032', '#E73827'], direction: 'to right', category: '优雅' },
  { name: 'Sherbert Deepest', colors: ['#F79D00', '#64F38C'], direction: 'to right', category: '优雅' },
  { name: 'Firewatch Deepest', colors: ['#CB2D3E', '#EF473A'], direction: 'to right', category: '优雅' },
  { name: 'Duluth Deepest', colors: ['#666666', '#999999'], direction: 'to right', category: '优雅' },
  { name: 'Kye Meh Deepest', colors: ['#83A4D4', '#B6FBFF'], direction: 'to right', category: '优雅' },
  { name: 'Starfall Deepest', colors: ['#F0C27B', '#4B1248'], direction: 'to right', category: '优雅' },
  { name: 'Dusk Deepest', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Deepest Glory', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Moonrise Deepest', colors: ['#DAE2F8', '#D6A4A4'], direction: 'to right', category: '优雅' },
  { name: 'Peach Deepest', colors: ['#ED4264', '#FFEDBC'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue Deepest Glory', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Noon Dusk Deepest', colors: ['#FF5E62', '#FF9966'], direction: 'to right', category: '优雅' },
  { name: 'Winter Deepest', colors: ['#E6DADA', '#274046'], direction: 'to right', category: '优雅' },
  { name: 'Nelson Deepest', colors: ['#F2709C', '#FF9472'], direction: 'to right', category: '优雅' },
  { name: 'Aubergine Deepest', colors: ['#AA076B', '#61045F'], direction: 'to right', category: '优雅' },
  { name: 'Post-it Deepest', colors: ['#FFFBD5', '#B20A2C'], direction: 'to right', category: '优雅' },
  { name: 'Hemlock Deepest', colors: ['#868F96', '#596164'], direction: 'to right', category: '优雅' },
  { name: 'Ocean View Deepest', colors: ['#A8CABA', '#5D4157'], direction: 'to right', category: '优雅' },
  { name: 'Joomla Deepest', colors: ['#1E3C72', '#2A5298'], direction: 'to right', category: '优雅' },
  { name: 'Christmas Deepest', colors: ['#2F7336', '#AA3A38'], direction: 'to right', category: '优雅' },
  { name: 'Minnesota Vikings Deepest', colors: ['#5614B0', '#DBD65C'], direction: 'to right', category: '优雅' },
  { name: 'Pizeel Deepest', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Haerlem Deepest', colors: ['#42E695', '#3BB2B8'], direction: 'to right', category: '优雅' },
  { name: 'Apple Deepest', colors: ['#F7FF00', '#DB36A4'], direction: 'to right', category: '优雅' },
  { name: 'Telegram Deepest', colors: ['#1C92D2', '#F2FCFE'], direction: 'to right', category: '优雅' },
  { name: 'Haiku Deepest', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer Deepest', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Deepest Glory', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Deepest Glory', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'YouTube Deepest', colors: ['#E52D27', '#B31217'], direction: 'to right', category: '优雅' },
  { name: 'Spotify Deepest', colors: ['#1ED760', '#1DB954'], direction: 'to right', category: '优雅' },
  { name: 'Twitch Deepest', colors: ['#6441A5', '#2A0845'], direction: 'to right', category: '优雅' },
  { name: 'WhatsApp Deepest', colors: ['#128C7E', '#075E54'], direction: 'to right', category: '优雅' },
  { name: 'Instagram Deepest', colors: ['#833AB4', '#FD1D1D', '#FCB045'], direction: 'to right', category: '优雅' },
  { name: 'Messenger Deepest', colors: ['#0084FF', '#00C6FF'], direction: 'to right', category: '优雅' },
  { name: 'Azure Dream Deepest Glory', colors: ['#2196F3', '#00BCD4'], direction: 'to right', category: '优雅' },
  { name: 'Honey Dew Deepest', colors: ['#43C6AC', '#F8FFAE'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Deepest Shine', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Kye Meh Deepest Shine', colors: ['#83A4D4', '#B6FBFF'], direction: 'to right', category: '优雅' },
  { name: 'Metropolis Deepest Shine', colors: ['#252233', '#ED4264'], direction: 'to right', category: '优雅' },
  { name: 'Orca Deepest Shine', colors: ['#44A08D', '#093637'], direction: 'to right', category: '优雅' },
  { name: 'Paradise Deepest Shine', colors: ['#22E1FF', '#1D8CF8'], direction: 'to right', category: '优雅' },
  { name: 'Pastel Orange Deepest Shine', colors: ['#FFB347', '#FFCC33'], direction: 'to right', category: '优雅' },
  { name: 'Purple Paradise Deepest Shine', colors: ['#1D2B64', '#F8CDDA'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue Deepest Shine', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Stellar Deepest Shine', colors: ['#7474BF', '#348AC7'], direction: 'to right', category: '优雅' },
  { name: 'Wedding Day Deepest Shine', colors: ['#40E0D0', '#FF8C00', '#FF0080'], direction: 'to right', category: '优雅' },
  { name: 'Indigo Night Deepest Shine', colors: ['#6366F1', '#A855F7'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Breeze Deepest Shine', colors: ['#0EA5E9', '#22D3EE'], direction: 'to right', category: '优雅' },
  { name: 'Sunset Glow Deepest Shine', colors: ['#F43F5E', '#FBBF24'], direction: 'to right', category: '优雅' },
  { name: 'Forest Mist Deepest Shine', colors: ['#10B981', '#34D399'], direction: 'to right', category: '优雅' },
  { name: 'Royal Purple Deepest Shine', colors: ['#7C3AED', '#DB2777'], direction: 'to right', category: '优雅' },
  { name: 'Morning Sky Deepest Shine', colors: ['#38BDF8', '#818CF8'], direction: 'to right', category: '优雅' },
  { name: 'Lush Green Deepest Shine', colors: ['#22C55E', '#10B981'], direction: 'to right', category: '优雅' },
  { name: 'Burning Orange Deepest Shine', colors: ['#F97316', '#EF4444'], direction: 'to right', category: '优雅' },
  { name: 'Slate Gray Deepest Shine', colors: ['#475569', '#1E293B'], direction: 'to right', category: '优雅' },
  { name: 'Mango Deepest Shine', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Mint Deepest Shine', colors: ['#00FF87', '#60EFFF'], direction: 'to right', category: '优雅' },
  { name: 'Vibrant Blue Deepest Shine', colors: ['#0575E6', '#021B79'], direction: 'to right', category: '优雅' },
  { name: 'Strawberry Deepest Shine', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Frost Deepest Shine', colors: ['#000428', '#004E92'], direction: 'to right', category: '优雅' },
  { name: 'Evening Sunshine Deepest Shine', colors: ['#B92B27', '#1565C0'], direction: 'to right', category: '优雅' },
  { name: 'Aqua Deepest Shine', colors: ['#134E5E', '#71B280'], direction: 'to right', category: '优雅' },
  { name: 'Cherry Deepest Shine', colors: ['#EB3349', '#F45C43'], direction: 'to right', category: '优雅' },
  { name: 'Mojito Deepest Shine', colors: ['#48B1BF', '#06BEB6'], direction: 'to right', category: '优雅' },
  { name: 'Coffee Deepest Shine', colors: ['#4B6CB7', '#182848'], direction: 'to right', category: '优雅' },
  { name: 'Kyoto Deepest Shine', colors: ['#C21500', '#FFC500'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer Deepest Shine', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Under the Lake Deepest Shine', colors: ['#0575E6', '#00F260'], direction: 'to right', category: '优雅' },
  { name: 'Elegant Gold Deepest', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Deep Ocean Blue Deepest', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Royal Velvet Deepest', colors: ['#AA076B', '#61045F'], direction: 'to right', category: '优雅' },
  { name: 'Midnight Spark Deepest', colors: ['#232526', '#414345'], direction: 'to right', category: '优雅' },
  { name: 'Golden Hour Shine Deepest', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Pure Sky Deepest Shine', colors: ['#7B4397', '#DC2430'], direction: 'to right', category: '优雅' },
  { name: 'Emerald Night Deepest Shine', colors: ['#02AAB0', '#00CDAC'], direction: 'to right', category: '优雅' },
  { name: 'Ocean Depth Shine Deepest Shine', colors: ['#000046', '#1CB5E0'], direction: 'to right', category: '优雅' },
  { name: 'Sweet Morning Shine Deepest', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Margo Shine Deepest', colors: ['#FF9A9E', '#FAD0C4'], direction: 'to right', category: '优雅' },
  { name: 'Viking Shine Deepest', colors: ['#2C3E50', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Lush Shine Deepest', colors: ['#A8E063', '#56AB2F'], direction: 'to right', category: '优雅' },
  { name: 'Reef Shine Deepest', colors: ['#00D2FF', '#3A7BD5'], direction: 'to right', category: '优雅' },
  { name: 'Neon Life Shine Deepest', colors: ['#B3FFAB', '#12FFF7'], direction: 'to right', category: '优雅' },
  { name: 'Magic Shine Deepest', colors: ['#59C173', '#A17FE0', '#5D26C1'], direction: 'to right', category: '优雅' },
  { name: 'Love Shine Deepest', colors: ['#FF0844', '#FFB199'], direction: 'to right', category: '优雅' },
  { name: 'Deep Space Shine Deepest', colors: ['#000000', '#434343'], direction: 'to right', category: '优雅' },
  { name: 'Metropolis Shine Deepest', colors: ['#252233', '#ED4264'], direction: 'to right', category: '优雅' },
  { name: 'Opa Shine Deepest', colors: ['#3D7EAA', '#FFE47A'], direction: 'to right', category: '优雅' },
  { name: 'Shroom Haze Shine Deepest', colors: ['#5C258D', '#4389A2'], direction: 'to right', category: '优雅' },
  { name: 'Kyoto Shine Deepest', colors: ['#C21500', '#FFC500'], direction: 'to right', category: '优雅' },
  { name: 'Misty Meadow Shine Deepest', colors: ['#215F00', '#E4E4D9'], direction: 'to right', category: '优雅' },
  { name: 'Stellar Shine Deepest', colors: ['#7474BF', '#348AC7'], direction: 'to right', category: '优雅' },
  { name: 'Celestial Shine Deepest', colors: ['#C33764', '#1D2671'], direction: 'to right', category: '优雅' },
  { name: 'Sunkist Shine Deepest', colors: ['#F2994A', '#F2C94C'], direction: 'to right', category: '优雅' },
  { name: 'Coal Shine Deepest', colors: ['#EB5757', '#000000'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Shine Deepest', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Shine Deepest', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'Forest Shine Deepest', colors: ['#5A3F37', '#2C7744'], direction: 'to right', category: '优雅' },
  { name: 'Tania Shine Deepest', colors: ['#12C2E9', '#C471ED', '#F64F59'], direction: 'to right', category: '优雅' },
  { name: 'Moorange Shine Deepest', colors: ['#FF5F6D', '#FFC371'], direction: 'to right', category: '优雅' },
  { name: 'Aqualicious Shine Deepest', colors: ['#50C9C3', '#96DED1'], direction: 'to right', category: '优雅' },
  { name: 'Tranquil Shine Deepest', colors: ['#EECDA3', '#EF629F'], direction: 'to right', category: '优雅' },
  { name: 'Shifter Shine Deepest', colors: ['#BC4E9C', '#F80759'], direction: 'to right', category: '优雅' },
  { name: 'Sun Horizon Shine Deepest', colors: ['#FDC830', '#F37335'], direction: 'to right', category: '优雅' },
  { name: 'Blood Red Shine Deepest', colors: ['#F85032', '#E73827'], direction: 'to right', category: '优雅' },
  { name: 'Sherbert Shine Deepest', colors: ['#F79D00', '#64F38C'], direction: 'to right', category: '优雅' },
  { name: 'Firewatch Shine Deepest', colors: ['#CB2D3E', '#EF473A'], direction: 'to right', category: '优雅' },
  { name: 'Duluth Shine Deepest', colors: ['#666666', '#999999'], direction: 'to right', category: '优雅' },
  { name: 'Kye Meh Shine Deepest', colors: ['#83A4D4', '#B6FBFF'], direction: 'to right', category: '优雅' },
  { name: 'Starfall Shine Deepest', colors: ['#F0C27B', '#4B1248'], direction: 'to right', category: '优雅' },
  { name: 'Dusk Shine Deepest', colors: ['#FFD200', '#F7971E'], direction: 'to right', category: '优雅' },
  { name: 'Skyline Shine Deepest Shine', colors: ['#1488CC', '#2B32B2'], direction: 'to right', category: '优雅' },
  { name: 'Moonrise Shine Deepest Shine', colors: ['#DAE2F8', '#D6A4A4'], direction: 'to right', category: '优雅' },
  { name: 'Peach Shine Deepest Shine', colors: ['#ED4264', '#FFEDBC'], direction: 'to right', category: '优雅' },
  { name: 'Sea Blue Shine Deepest Shine Glory', colors: ['#2B5876', '#4E4376'], direction: 'to right', category: '优雅' },
  { name: 'Noon Dusk Shine Deepest Shine', colors: ['#FF5E62', '#FF9966'], direction: 'to right', category: '优雅' },
  { name: 'Winter Shine Deepest Shine', colors: ['#E6DADA', '#274046'], direction: 'to right', category: '优雅' },
  { name: 'Nelson Shine Deepest Shine', colors: ['#F2709C', '#FF9472'], direction: 'to right', category: '优雅' },
  { name: 'Aubergine Shine Deepest Shine', colors: ['#AA076B', '#61045F'], direction: 'to right', category: '优雅' },
  { name: 'Post-it Shine Deepest Shine', colors: ['#FFFBD5', '#B20A2C'], direction: 'to right', category: '优雅' },
  { name: 'Hemlock Shine Deepest Shine', colors: ['#868F96', '#596164'], direction: 'to right', category: '优雅' },
  { name: 'Ocean View Shine Deepest Shine', colors: ['#A8CABA', '#5D4157'], direction: 'to right', category: '优雅' },
  { name: 'Joomla Shine Deepest Shine', colors: ['#1E3C72', '#2A5298'], direction: 'to right', category: '优雅' },
  { name: 'Christmas Shine Deepest Shine', colors: ['#2F7336', '#AA3A38'], direction: 'to right', category: '优雅' },
  { name: 'Minnesota Vikings Shine Deepest Shine', colors: ['#5614B0', '#DBD65C'], direction: 'to right', category: '优雅' },
  { name: 'Pizeel Shine Deepest Shine', colors: ['#11998E', '#38EF7D'], direction: 'to right', category: '优雅' },
  { name: 'Haerlem Shine Deepest Shine', colors: ['#42E695', '#3BB2B8'], direction: 'to right', category: '优雅' },
  { name: 'Apple Shine Deepest Shine', colors: ['#F7FF00', '#DB36A4'], direction: 'to right', category: '优雅' },
  { name: 'Telegram Shine Deepest Shine', colors: ['#1C92D2', '#F2FCFE'], direction: 'to right', category: '优雅' },
  { name: 'Haiku Shine Deepest Shine', colors: ['#FD746C', '#FF9068'], direction: 'to right', category: '优雅' },
  { name: 'Neuromancer Shine Deepest Shine', colors: ['#F953C6', '#B91D73'], direction: 'to right', category: '优雅' },
  { name: 'Flickr Shine Deepest Shine Glory', colors: ['#FF0084', '#33001B'], direction: 'to right', category: '优雅' },
  { name: 'Vine Shine Deepest Shine Glory', colors: ['#00BF8F', '#001510'], direction: 'to right', category: '优雅' },
  { name: 'YouTube Shine Deepest Shine', colors: ['#E52D27', '#B31217'], direction: 'to right', category: '优雅' },
  { name: 'Spotify Shine Deepest Shine', colors: ['#1ED760', '#1DB954'], direction: 'to right', category: '优雅' },
  { name: 'Twitch Shine Deepest Shine', colors: ['#6441A5', '#2A0845'], direction: 'to right', category: '优雅' },
  { name: 'WhatsApp Shine Deepest Shine', colors: ['#128C7E', '#075E54'], direction: 'to right', category: '优雅' },
  { name: 'Instagram Shine Deepest Shine', colors: ['#833AB4', '#FD1D1D', '#FCB045'], direction: 'to right', category: '优雅' },
  { name: 'Messenger Shine Deepest Shine', colors: ['#0084FF', '#00C6FF'], direction: 'to right', category: '优雅' },
  { name: 'Azure Dream Shine Deepest Shine Glory', colors: ['#2196F3', '#00BCD4'], direction: 'to right', category: '优雅' },
  { name: 'Honey Dew Shine Deepest Shine', colors: ['#43C6AC', '#F8FFAE'], direction: 'to right', category: '优雅' },
  // 小清新分类
  { name: 'Lemon Sorbet', colors: ['#FFF9C4', '#FBC02D'], direction: 'to right', category: '小清新' },
  { name: 'Sky Sparkle', colors: ['#E1F5FE', '#03A9F4'], direction: 'to right', category: '小清新' },
  { name: 'Peach Sorbet', colors: ['#FFE0B2', '#FF7043'], direction: 'to right', category: '小清新' },
  { name: 'Spring Breeze', colors: ['#F1F8E9', '#8BC34A'], direction: 'to right', category: '小清新' },
  { name: 'Aqua Mint', colors: ['#E0F2F1', '#009688'], direction: 'to right', category: '小清新' },
  { name: 'Pink Lemonade', colors: ['#FCE4EC', '#F06292'], direction: 'to right', category: '小清新' },
  { name: 'Morning Mist', colors: ['#F3E5F5', '#BA68C8'], direction: 'to right', category: '小清新' },
  { name: 'Sunny Meadow', colors: ['#FFFDE7', '#CDDC39'], direction: 'to right', category: '小清新' },
  { name: 'Blue Lagoon', colors: ['#E0F7FA', '#00BCD4'], direction: 'to right', category: '小清新' },
  { name: 'Sweet Peach', colors: ['#FFF3E0', '#FFB74D'], direction: 'to right', category: '小清新' },
  { name: 'Cool Breeze', colors: ['#E8EAF6', '#5C6BC0'], direction: 'to right', category: '小清新' },
  { name: 'Green Tea', colors: ['#E8F5E9', '#4CAF50'], direction: 'to right', category: '小清新' },
  { name: 'Rose Petal', colors: ['#F8BBD0', '#E91E63'], direction: 'to right', category: '小清新' },
  { name: 'Lavender Field', colors: ['#EDE7F6', '#673AB7'], direction: 'to right', category: '小清新' },
  { name: 'Ocean Pearl', colors: ['#B2EBF2', '#0097A7'], direction: 'to right', category: '小清新' },
  { name: 'Summer Glow', colors: ['#FFF9C4', '#FFEB3B'], direction: 'to right', category: '小清新' },
  { name: 'Mint Leaf', colors: ['#C8E6C9', '#2E7D32'], direction: 'to right', category: '小清新' },
  { name: 'Soft Sky', colors: ['#BBDEFB', '#1976D2'], direction: 'to right', category: '小清新' },
  { name: 'Peach Blossom', colors: ['#FFE0B2', '#FB8C00'], direction: 'to right', category: '小清新' },
  { name: 'Fresh Air', colors: ['#B2DFDB', '#00796B'], direction: 'to right', category: '小清新' },
  { name: 'Pink Rose', colors: ['#FCE4EC', '#D81B60'], direction: 'to right', category: '小清新' },
  { name: 'Lilac Dream', colors: ['#D1C4E9', '#512DA8'], direction: 'to right', category: '小清新' },
  { name: 'Aqua Marine', colors: ['#B2EBF2', '#00ACC1'], direction: 'to right', category: '小清新' },
  { name: 'Sunny Day', colors: ['#FFF9C4', '#FBC02D'], direction: 'to right', category: '小清新' },
];

const GradientCollection: React.FC = () => {
  const [activeCategory, setActiveCategory] = useState<Category>('CSS');
  const addToast = useToastStore((state) => state.addToast);

  const filteredGradients = gradients.filter(g => g.category === activeCategory);

  const copyCSS = async (g: GradientInfo) => {
    const css = `background: linear-gradient(${g.direction}, ${g.colors.join(', ')});`;
    const success = await copyToClipboard(css);
    if (success) {
      addToast(`已成功复制 CSS 代码: ${css}`);
    } else {
      addToast('复制失败', 'error');
    }
  };

  const copyHex = async (hex: string) => {
    const success = await copyToClipboard(hex);
    if (success) {
      addToast(`已成功复制色值: ${hex.toUpperCase()}`);
    } else {
      addToast('复制失败', 'error');
    }
  };


  const categories: { id: Category; icon: React.ReactNode; label: string }[] = [
    { id: 'CSS', icon: <Layout size={16} />, label: 'CSS 渐变' },
    { id: '小清新', icon: <Sparkles size={16} />, label: '小清新' },
    { id: '优雅', icon: <Palette size={16} />, label: '优雅风' },
  ];

  return (
    <PageContainer title="渐变色大全">
      {/* Category Tabs */}
      <div className="flex flex-wrap items-center gap-3 mb-12">
        {categories.map((cat) => (
          <button
            key={cat.id}
            onClick={() => setActiveCategory(cat.id)}
            className={`flex items-center gap-2 px-4 py-1.5 rounded-full text-xs font-bold transition-all ${
              activeCategory === cat.id
                ? 'bg-[#10b981] text-white shadow-md'
                : 'bg-[#f0f9ff] text-[#0d9488] hover:bg-[#e0f2fe]'
            }`}
          >
            <span>{cat.id}</span>
          </button>
        ))}
        <div className="ml-auto text-sm text-slate-400 font-medium hidden md:block">
          共收录 {gradients.length} 种方案，当前分类 {filteredGradients.length} 种
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        {filteredGradients.map((g, i) => (
          (activeCategory === '小清新' || activeCategory === '优雅') ? (
            <div 
              key={`${activeCategory}-${i}`} 
              className="relative overflow-hidden rounded-[32px] shadow-sm group hover:shadow-2xl transition-all duration-500 border border-slate-100 bg-white p-3"
            >
              {/* 渐变预览区域 */}
              <div 
                className="w-full h-48 rounded-[24px] cursor-pointer relative overflow-hidden group-hover:scale-[0.98] transition-transform duration-500"
                style={{ background: `linear-gradient(${g.direction}, ${g.colors.join(', ')})` }}
                onClick={() => copyCSS(g)}
              >
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-colors duration-500" />
                <div className="absolute bottom-4 left-4 right-4">
                  <span className="text-white font-black text-lg sm:text-xl drop-shadow-lg tracking-tight opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-500">
                    {g.name}
                  </span>
                </div>
              </div>
              
              {/* 底部操作栏 */}
              <div className="mt-3 px-2 flex items-center justify-between">
                <div className="flex -space-x-2">
                  {g.colors.map((c, colorIdx) => (
                    <motion.button
                      key={colorIdx}
                      whileHover={{ zIndex: 10, scale: 1.2, y: -4 }}
                      onClick={() => copyHex(c)}
                      className="w-8 h-8 rounded-full border-2 border-white shadow-sm transition-transform relative"
                      style={{ backgroundColor: c }}
                      title={`复制颜色: ${c}`}
                    />
                  ))}
                </div>
                <div className="flex flex-col items-end">
                  <span className="text-[10px] font-black text-slate-300 uppercase tracking-widest leading-none mb-1">Gradient Name</span>
                  <span className="text-sm font-bold text-slate-600 tracking-tight">{g.name}</span>
                </div>
              </div>
            </div>
          ) : (
            <div 
              key={`${activeCategory}-${i}`} 
              className="overflow-hidden rounded-lg shadow-sm group hover:shadow-xl transition-all border border-slate-100 bg-white"
            >
              {/* 渐变预览区域 */}
              <div 
                className="w-full h-36 cursor-pointer"
                style={{ background: `linear-gradient(${g.direction}, ${g.colors.join(', ')})` }}
                onClick={() => copyCSS(g)}
                title="点击复制 CSS 代码"
              />
              {/* 底部灰色操作栏 */}
              <div 
                className="bg-[#f1f5f9] h-10 flex items-center justify-center cursor-pointer hover:bg-indigo-600 hover:text-white transition-all group/btn"
                onClick={() => copyCSS(g)}
              >
                <span className="text-xs font-medium text-slate-500 group-hover/btn:text-white">复制CSS</span>
              </div>
            </div>
          )
        ))}
      </div>

      {/* About Section */}
      <div className="mt-12 bg-indigo-50/50 p-8 rounded-xl border border-indigo-100 space-y-4 max-w-5xl mx-auto">
        <div className="flex items-center gap-2 text-indigo-600 font-bold text-lg">
          <Info size={20} />
          <h3>关于渐变色大全介绍:</h3>
        </div>
        <div className="space-y-3 text-indigo-800/80 text-sm leading-relaxed font-medium">
          <p>1、此工具收录了多种精心设计的线性渐变方案，分为 CSS 渐变、小清新、优雅风三大类。</p>
          <p>2、每个渐变卡片都清晰展示了其包含的原始色值和视觉效果，您可以根据分类快速筛选出心仪的色彩组合。</p>
          <p>3、小清新及优雅风分类支持点击下方小色块直接复制色值，点击预览区域可复制 CSS 代码。</p>
          <p>4、CSS 渐变分类点击“复制 CSS”栏即可一键获取完整的 CSS 代码，轻松应用到您的 Web 开发或设计工作中。</p>
        </div>
      </div>
    </PageContainer>
  );
};

export default GradientCollection;
